# -*- coding: utf-8 -*-
##############################################################################
#
#    odoo, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
{
        "name" : "movimientos",
        "version" : "13.1",
        "author" : "Beatriz Coronel",
        "website" : "",
        "category" : "Movimientos",
        "description": """  """,
        "depends" : ['base','bienes','vehiculos'],
        "init_xml" : [ ],
        "demo_xml" : [ ],
        "update_xml" : ['security/groups.xml',
                         'views/movimientos_menu_view.xml',
                         'views/tipo_movimientos_view.xml',
                         'views/ente_externo_view.xml',
                         'views/reasignacion_movimientos_view.xml',   
                      #   'views/desincorporacion_movimientos_view.xml',                         
                                 
                     #    'views/movimientos_view.xml',
                     #    'views/mov_vehiculos_view.xml',
                         #'views/workflow_movdeta.xml',
                         'data/tipos_movimientos.xml',

                         #'views/template_reporte_movDeta.xml',                       
                         #'report/report_movdeta.xml',
                         'security/ir.model.access.csv'],
        "installable": True
}
