
# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
# from osv import fields,osv --- <8.0.X
from odoo import api, fields, models
from odoo.exceptions import ValidationError
from datetime import date, datetime,timedelta
#from odoo.addons.jasper_reports import jasper_report
#from odoo import pooler
from datetime import  datetime
from time import time
formatter_string = "%d-%m-%y" 
#from tools.translate import_
#from odoo import tools
import sys
#reload(sys)
#sys.setdefaultencoding("utf-8")
#Importamos la libreria logger
import logging
#Definimos la Variable Global
_logger = logging.getLogger(__name__)


class ubicacion_fisica(models.Model):
    """Registra  la Ubicación Fisica del Bien"""
    _name = 'ubicacion_fisica'
    _rec_name = 'ubicacion_fisica_nombre'
    ubicacion_fisica_nombre = fields.Char('Nombre de la Ubicación Física del Bien',size=100,required=True, help='Registra el Nombre de la Categoria de Oficina (SUDEBIP)')
    ubicacion_fisica_codigo = fields.Char(string='Codigo de la Ubicacion Física',
    				size=3,
    				default='New',
                    required=True,
    				help='Registra el Codigo de la Ubicacion Física (Interno)')


    _sql_constraints = [('ubicacion_fisica_nombre', 'unique(ubicacion_fisica_nombre)', 'El Nombre debe se único!')]





    @api.model  
    def create(self,vals):
       if vals.get('ubicacion_fisica_codigo',  'New') == 'New' or '':
          vals['ubicacion_fisica_codigo'] = self.env['ir.sequence'].next_by_code(
           'self.ubicacion_fisica_codigo')  or 'New'
          
       result = super(ubicacion_fisica, self).create(vals)
       return result 


   #****************Tipos de Estatus de Inventario*******************#
class tipo_estatus_inventario(models.Model):
    """Registra los Tipos de estatus de inventario de bienes"""
    _name = 'tipo_estatus_inventario'
    _rec_name = 'nom_estatus'
    nom_estatus = fields.Char('Nombre del Estatus del Inventario',size=100,required=True, help='Registra el Nombre del Movimiento')
    cod_estatus = fields.Char('Codigo del Estatus del Inventario',size=100, required=True, help='Registra el Codigo del Estatus de Inventario')
    _sql_constraints = [('nom_estatus', 'unique(nom_estatus)', 'El Nombre del Estatus del Inventario debe ser Unico!')]  

